### ISSUE TITLE
Add interactive mode to allow user input and execution control

### ISSUE THREAD

**Issue by ManuelZierl** [ManuelZierl/fellow#33]
### Description

Currently, `fellow` operates in a linear loop, where the AI receives messages, reasons, calls commands, and terminates after an `END` message. However, users might want to **intervene during execution**, clarify intentions, or **correct agent behavior in real time**.

This feature proposes adding an **interactive mode** that enables user feedback **at any point during execution**, and allows the agent to ask the user questions as part of its reasoning process.

### Goals

- [ ] Introduce a **configurable interactive mode** (`config.interactive.enabled: true`)
- [ ] Allow the user to **interrupt the loop anytime** by typing input (e.g., stdin, keypress via `config.interactive.interrupt: true`)
- [ ] Feed that user input as a message back to the AI (clarification, correction, etc.)
- [ ] Allow the AI to **ask the user questions mid-process** (e.g., “Should I proceed?” via `config.interactive.consultation: true`)
      for this a new command `ask_question` should be introduced
- [ ] When the AI returns `"END"`, **prompt the user for a new instruction** instead of exiting (via `config.interactive.final_review: true`)
- [ ] Preserve full compatibility with existing YAML-based task config

### Config Proposal

```yaml
interactive:
  enabled: true  # enables interactive mode
  interrupt: true # allowes user interuption during working process
  consultation: true # allows ai to ask questions to the user
  final_review: true # Instead of ending the run user can demand new prompt
```
