### ISSUE TITLE
Add urls to pyproject.toml

### ISSUE THREAD

**Issue by ManuelZierl** [ManuelZierl/fellow#35]
```toml
urls = {
  "Homepage" = "https://github.com/ManuelZierl/fellow",
  "Source" = "https://github.com/ManuelZierl/fellow",
  "Tracker" = "https://github.com/ManuelZierl/fellow/issues"
}
```
