### ISSUE TITLE
Add Support for Logical Command Groups in Configuration

### ISSUE THREAD

**Issue by ManuelZierl** [ManuelZierl/fellow#38]
Context:
The current configuration system in default_fellow_config.yml allows specifying a flat list of commands under the commands: key. This works well but lacks flexibility when adapting to different types of projects (e.g., Python vs. Node.js vs. Rust).

Problem:
Agents working in different environments need different sets of tools. For example:
	•	A Python project may require commands like run_pytest, format_black, list_requirements
	•	A Node.js project might use npm_install, run_eslint, build_vue

Currently, all commands must be listed manually, and there’s no mechanism to group or switch between them contextually or semantically.

⸻

Proposed Solution: Logical Command Groups

Introduce a new configuration section:
```yaml
command_groups:
  python:
    - run_pytest
    - format_black
    - extract_functions
  nodejs:
    - npm_install
    - run_eslint
    - extract_js_functions

# Then select active group:
commands: "@group:python"
```

Alternatively, allow group merging:

```yaml
commands:
  - "@group:python"
  - custom_command_1
```

This would:
	•	Promote reuse
	•	Allow easier onboarding (one-line switches per project)
	•	Encourage separation of environment-specific logic

⸻

Implementation Notes
	•	Group resolution could happen at config-load time.
	•	Validation should ensure group names exist.
	•	Could be extended with conditional logic in the future (e.g., based on files in the repo).

⸻

Benefits
	•	Cleaner configuration for complex workflows
	•	Better developer experience
	•	Aligns with the modular nature of Fellow’s agent design
