### ISSUE TITLE
Refactor OpenAIClient into a pluggable interface and add support for other AI providers

### ISSUE THREAD

**Issue by ManuelZierl** [ManuelZierl/fellow#43]
Currently, the system is tightly coupled to OpenAIClient, which handles all API interactions and memory management. To improve extensibility and make the tool provider-agnostic, we should refactor this into a client interface. This would allow users to implement or plug in different AI backends.

###  Goals:
- [ ] Convert OpenAIClient into a base interface (e.g. AIClient)
- [ ] Move OpenAI-specific logic to OpenAIClient implementation
- [ ] Identify and create separate tickets for implementing support for major AI providers, such as:
     - Anthropic (Claude)
     - Mistral (via openrouter.ai, or direct API)
     - Google Gemini (if API access is available)
     - Others?
- [ ] Add provider selection to the config file
- [ ] Allow users to implement and configure custom AI clients, enabling support for local LLMs or bespoke agent logic

```yml
ai_client:
  client: openai
  config:
    memory_max_tokens: 15000
    summary_memory_max_tokens: 15000
    model: "gpt-4o"
```
